//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PcToplamaEntities : DbContext
    {
        public PcToplamaEntities()
            : base("name=PcToplamaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_City> tbl_City { get; set; }
        public virtual DbSet<tbl_CPU> tbl_CPU { get; set; }
        public virtual DbSet<tbl_Customer> tbl_Customer { get; set; }
        public virtual DbSet<tbl_Disk> tbl_Disk { get; set; }
        public virtual DbSet<tbl_Ekran> tbl_Ekran { get; set; }
        public virtual DbSet<tbl_GPU> tbl_GPU { get; set; }
        public virtual DbSet<tbl_kasa> tbl_kasa { get; set; }
        public virtual DbSet<tbl_Keyboard> tbl_Keyboard { get; set; }
        public virtual DbSet<tbl_Kulaklık> tbl_Kulaklık { get; set; }
        public virtual DbSet<tbl_MotherBoard> tbl_MotherBoard { get; set; }
        public virtual DbSet<tbl_mouse> tbl_mouse { get; set; }
        public virtual DbSet<tbl_Order> tbl_Order { get; set; }
        public virtual DbSet<tbl_PSU> tbl_PSU { get; set; }
        public virtual DbSet<tbl_RAM> tbl_RAM { get; set; }
        public virtual DbSet<tbl_Socket> tbl_Socket { get; set; }
    }
}
