//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MotherBoard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_MotherBoard()
        {
            this.tbl_Order = new HashSet<tbl_Order>();
        }
    
        public int MB_Id { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Soket_Id { get; set; }
        public string Full_Ad { get; set; }
        public string Yapı { get; set; }
        public string Bellek_Tip { get; set; }
        public Nullable<byte> Ram_Slot_sayısı { get; set; }
        public Nullable<int> Stok { get; set; }
    
        public virtual tbl_Socket tbl_Socket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Order> tbl_Order { get; set; }
    }
}
